# Generated by Django 4.2.1 on 2023-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Literatura', 'Literatura'), ('Cocina', 'Cocina'), ('Deportes', 'Deportes')], max_length=50),
        ),
    ]
