# Generated by Django 4.2.1 on 2023-05-31 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_usuario_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(related_name='blog_publicaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
