# Generated by Django 4.2.1 on 2023-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicacion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
