# Generated by Django 4.2.1 on 2023-06-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='/static/core/img/default.jpg', upload_to=''),
        ),
    ]
