# Generated by Django 4.2.1 on 2023-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='likepublicacion',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likepublicacion',
            name='publicacion',
        ),
        migrations.DeleteModel(
            name='DesL',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='LikePublicacion',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
