# Generated by Django 4.2.1 on 2023-06-14 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_publicaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
