# Generated by Django 4.2.1 on 2023-06-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comentario_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
    ]
