# Generated by Django 4.0.4 on 2023-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_catego', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_catego', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_com', models.BigIntegerField(primary_key=True, serialize=False)),
                ('texto_com', models.CharField(max_length=500)),
                ('f_com', models.DateField()),
                ('status_com', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id_lp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('like_id_like', models.BigIntegerField()),
            ],
            options={
                'db_table': 'like_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id_like', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_usua', models.BigIntegerField()),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('texto_post', models.CharField(max_length=2000)),
                ('f_crea', models.DateField()),
                ('estatus_post', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_pregu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_usua', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('rut', models.BigIntegerField()),
                ('f_nacim', models.DateField()),
                ('correo', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=15)),
                ('res_segu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
