# Generated by Django 4.1.5 on 2023-05-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likepost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_foto', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='DesL',
            fields=[
                ('id_pc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comentario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
        ),
    ]
