# Generated by Django 4.1.5 on 2023-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_desl_comentario_remove_desl_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='estatus_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='f_crea',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
